### PR TITLE
samples/net/simple: Run in user mode instead of kernel mode

### PR DESCRIPTION
**Pull request by xyzshantaram**
Kernel mode samples did not run correctly. This PR switches the sample over to run in userland, and changes some heap settings as well.
I'd be willing to fix this for the other samples as well.

### CODE REVIEW

**Review by diamant3 — APPROVED** [review]
Thanks for the PR!

Wouter mostly fixed the samples, super thanks to him. If you find another issue in the samples, feel free to make a PR and that would be much appreciated.

**Comment by joel16** [comment]
> Thanks for the PR!
> 
> Wouter mostly fixed the samples, super thanks to him. If you find another issue in the samples, feel free to make a PR and that would be much appreciated.

I believe those fixes are just build fixes for GCC 14. There may be some samples that are still borked or haven't been updated since some ancient cfw.

**Comment by diamant3** [comment]
> I believe those fixes are just build fixes for GCC 14. There may be some samples that are still borked or haven't been updated since some ancient cfw.

yes you're right joel16 those fixes i said are from this PR #203. Feel free to make a PR for those who want to fix them, it's really appreciated ❤️

**Comment by rofl0r** [comment]
it'd be great if you didn't mix whitespace changes with functional changes. makes it hard to see what was actually needed to fix the issue.

**Comment by xyzshantaram** [comment]
Sorry, yeah, that was my bad - I had a pretty nightmarish experience trying to turn off clang-format but leave the language server on, and I'd committed my changes before realising the whitespace issue, so I settled for configuring it as close to the original as possible, but the code style was a bit all over the place.
  

  
If the maintainers would be interested I would love to set up formatting for the entire repo, perhaps even as a CI step.
  

  
My apologies once again for the trouble.
  

  

  
  
  
  
>

**Pull request merged**
