### PR TITLE
Add SDL2 examples

### PR DESCRIPTION
**Pull request by bucanero**
While learning the basics of pspdev, I found some SDL2 examples on https://pspdev.github.io/ , but those samples where not available on pspsdk.

To help newcomers, I'm adding these files to the pspsdk samples (and to avoid copy/paste issues or mistakes)

sdl examples credits
- https://github.com/pspdev/pspdev.github.io/pull/9
- https://github.com/pspdev/pspdev.github.io/pull/12

### CODE REVIEW

**Comment by sharkwouter** [comment]
Hey @bucanero, thanks for this PR. I do think it's good to have these examples available, but I would say that this is not the place, since they require specific libraries which are not available in this repository or during the testing. I think it could make sense to add them to the packages in psp-packages instead.

**Comment by bucanero** [comment]
> Hey @bucanero, thanks for this PR. I do think it's good to have these examples available, but I would say that this is not the place, since they require specific libraries which are not available in this repository or during the testing. I think it could make sense to add them to the packages in psp-packages instead.

thanks for the feedback @sharkwouter 

I was checking the `psp-packages` repo, but I'm not sure where I should add these examples.
Could they be part of the SDL2 script? or do you have any other suggestions?

Just asking before opening a new PR to avoid issues

**Comment by sharkwouter** [comment]
You'd add it to the directory in which the PSPBUILD for the package is located, then add it in sources in the PSPBUILD and to sha256sums you add a 'SKIP' for every file you've added. Then the package step should put the sample in a location which makes sense, probably something like `$pkgdir/psp/share/samples/$pkgname`

**Comment by bucanero** [comment]
> You'd add it to the directory in which the PSPBUILD for the package is located, then add it in sources in the PSPBUILD and to sha256sums you add a 'SKIP' for every file you've added. Then the package step should put the sample in a location which makes sense, probably something like `$pkgdir/psp/share/samples/$pkgname`

great, thanks for the feedback. I've moved this PR to `draft`, and I'll create a new PR on `psp-packages` as you suggested. Once I have a new PR I'll link and close this draft.

**Pull request closed without merging**
