### PR TITLE
add C++ helloworld sample

### PR DESCRIPTION
**Pull request by rofl0r**
mainly to test #194 using the official toolchain from docker.

### CODE REVIEW

**Comment by wally4000** [comment]
Happy to approve this but if it's a hello world example, shouldn't it also have hello world? :)

**Comment by bucanero** [comment]
looks like the CI build check is also failing.

**Comment by rofl0r** [comment]
before this can be merged, build.mak needs to be adapted to support using g++ as linker for c++ code. i posted a gnu make snippet that can achieve this in the now closed pr by @diamant3 - he's also the author of this "hello world" example.

**Comment by diamant3** [comment]
Hello @rofl0r feel free to open an issue or discussion that focuses on what you've discussed with fjtrujy last time.

**Comment by diamant3** [comment]
Hello @rofl0r, Are you still working on this or can be this closed now?

**Pull request closed without merging**
