### PR TITLE
gu: speedup

### PR DESCRIPTION
**Pull request by Crow-bar**
Inline expansion
Adds several frames in heavy graphics applications

https://github.com/pspdev/pspsdk/pull/168

### CODE REVIEW

**Comment by sharkwouter** [comment]
It looks fine, but what makes it faster? It looks like the same code to me.

**Comment by Crow-bar** [comment]
> It looks fine, but what makes it faster? It looks like the same code to me.

Are you seriously?

**Comment by Crow-bar** [comment]
stack work and unnecessary jump instructions... inlining removes this

**Comment by sharkwouter** [comment]
No need to be mean about it. I was expecting the compiler to be able to deal with this, I'm no expert on how the compiler works. That's why I was a bit confused and thought I had missed something while looking at the code.

I'll give this a test and merge it.

**Review by sharkwouter — APPROVED** [review]

**Comment by sharkwouter** [comment]
Thanks for contributing, this is a really cool change!

**Comment by Crow-bar** [comment]
> No need to be mean about it. I was expecting the compiler to be able to deal with this, I'm no expert on how the compiler works. That's why I was a bit confused and thought I had missed something while looking at the code.
> 
> I'll give this a test and merge it.

Sorry, i didn't mean to put it that way.
Ok, thank you

**Comment by rofl0r** [comment]
not so cool are the 50 lines with gratuitous whitespace changes.

**Comment by rofl0r** [comment]
> Alignment, for readability

that's nothing but a personal style preference. if done, it should be a separate commit. like this you only get a hard time seeing the actual relevant changes of the commit.

**Comment by Crow-bar** [comment]
> > Alignment, for readability
> 
> that's nothing but a personal style preference. if done, it should be a separate commit. like this you only get a hard time seeing the actual relevant changes of the commit.

I agree with you

**Comment by davidgfnet** [comment]
Thanks!
We should really focus on getting good LTO support. It does help in things like this. And it's (in many cases) "free" optimization :)

**Pull request merged**
